### PR TITLE
add eid-FI option

### PR DESCRIPTION
**Pull request by bogdan-niculescu-sch**
Add eID for Sweden and Finland to sdk-example

### CODE REVIEW

**Review by rafal-kanski-stp — APPROVED** [review]
This looks good to me 👏 , but please test it out locally. I do not have access to client/secrets so it would be very time-consuming for me right now 😢

**Review by rafal-kanski-stp — APPROVED** [review]
good catch

**Comment by bogdan-niculescu-sch** [comment]
added a few changes since last commit.

Was also able to test, and FI works well

**Review by hunger-programmer — APPROVED** [review]

**Review by michal-oleniacz-stp — APPROVED** [review]
LGTM

**Review by rafal-kanski-stp — APPROVED** [review]

**Pull request merged**
